export const faqs = [
  { q: "Can I work abroad without experience?", a: "Some jobs ask for experience and some do not. It depends on the employer. Tell us what you have done before and we will explain what may be possible." },
  { q: "Do I need a passport?", a: "Yes. You cannot travel to another country without a valid passport. If you do not have one, tell us and we will explain the next step." },
  { q: "Do I need a medical examination?", a: "Many jobs and countries require a medical. If yours does, we explain where to go, what to carry and what to expect. See our Medical Guide." },
  { q: "What is a work visa?", a: "A work visa is official permission to enter and work in a country for a stated period. It is given by that country's authorities, not by us." },
  { q: "Who approves my visa?", a: "The embassy, visa centre or immigration authority of the country decides. We can guide and assist, but we cannot approve a visa." },
  { q: "How long does the process take?", a: "It depends on the employer, the country and the paperwork. Some steps are quick and some take weeks. We will not promise an exact time." },
  { q: "How much does it cost?", a: "Costs depend on the destination, job, employer, visa type, medical requirements, documentation and travel. Ask us for the details in writing before you pay anything." },
  { q: "Can I choose my country?", a: "You can tell us where you would like to go. We can only help where there is an approved opportunity or service available." },
  { q: "Can I choose my job?", a: "You can tell us the job you want. Availability depends on current employer demand and your skills and documents." },
  { q: "Can I apply for a job through WhatsApp?", a: "You can start a conversation on WhatsApp on +254 702 925 132. Our team will explain the next step. Only use this official number." },
  { q: "How do I know a job is genuine?", a: "Ask for the details in writing, confirm the company's contact information, read the contract and never send money to a personal number. Read our Safety page." },
  { q: "Do you guarantee employment?", a: "No. Nobody honest can guarantee a job. We explain opportunities and requirements. Employers make the final hiring decision." },
  { q: "Do you guarantee a visa?", a: "No. Visa decisions are made by the relevant authorities. We provide guidance and assistance." },
  { q: "Can I travel for tourism?", a: "Yes, you can ask us about travel for tourism. We explain the documents and visa steps for your destination." },
  { q: "Can you book my flight?", a: "We can help coordinate suitable flight options. We do not promise the cheapest fare." },
  { q: "Can you help with relocation?", a: "Yes. We can help with documents, flight, airport arrangements, accommodation where available, and arrival guidance." },
  { q: "What happens at the airport?", a: "You check in, drop your bags, go through security and immigration, then board. Our Airport Guide explains every step." },
  { q: "What happens after I arrive?", a: "It depends on your arrangement. It may include pickup, an employer representative, accommodation, workplace instructions and orientation." },
  { q: "What documents should I prepare?", a: "Usually a passport, national ID, photographs, CV and certificates where relevant. Your exact list depends on your destination, job and employer." },
  { q: "What if I do not understand the process?", a: "That is completely fine. You do not need to understand everything before contacting us. Ask us and we will explain." },
  { q: "Can businesses partner with Kenkos?", a: "Yes. Employers, agencies, training institutions, travel partners and logistics companies can contact us to discuss a partnership." },
];
